### ISSUE TITLE
ogdc-runner initial spike

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/ogdc-runner#1]
* Initialize python library skeleton
    * Publish to PyPI
* Initialize docs skeleton
    * Document "simple recipe" API
    * Placeholder for "raw recipe" API
* Implement simple recipe workflow end-to-end so `ogdc-runner` can be tested as a component
    * See: https://github.com/QGreenland-Net/simple-recipe-representation-exploration
* Test new recipes implemented in https://github.com/QGreenland-Net/.github/issues/28

**Comment by trey-stafford** [comment]
https://github.com/QGreenland-Net/ogdc-runner/pull/6
