### ISSUE TITLE
ogdc-runner: add support for rendering "simple" recipe into argo workflow

### ISSUE THREAD

**Issue by trey-stafford** [QGreenland-Net/ogdc-runner#25]
Add support for "simple" recipes. This would let the runner take a "simple" recipe (e.g., see https://github.com/QGreenland-Net/ogdc-recipes/tree/411e41f2f7e6310044cfc26adafb741eb77982e1/recipes/sea-ice-conc) and convert it into an argo workflow that can be submitted to the cluster.

* [x] Add support to render a "simple" recipe into an argo workflow and submit it to the cluster
* [x] Add unit test(s) for validation and rendering of "simple" recipe into argo workflow
* [ ] Add an integration test that asserts successful workflow execution given a "simple" recipe.

**Comment by rmarow** [comment]
the simple workflow will be the `seal-tags` workflow which has presence in the argo exploration repo already
