### ISSUE TITLE
What's the best way for us to submit a recipe to the cluster?

### ISSUE THREAD

**Issue by mfisher87** [QGreenland-Net/ogdc-runner#5]
We need to define an interface for users to author recipes. Which part do they write? How do we take the user part and make it in to a machine-understandable workflow to submit to the cluster?

Right now we're using templating, and we really don't like it because it's hard to validate. Trey is exploring an alternate approach on a branch (`reconsider-recipe-templating`).

We think we should explore multiple approaches to user recipe design. For example, if we use a context manager to load the parsl configuration (e.g. executor, provider), do we call it under the hood or expect the user to use the context manager? What will enable the typechecker to do the best validation on the recipe?

**Comment by trey-stafford** [comment]
This was specific to using parsl. We now plan to use Argo and will evaluate how recipes are submitted for that separately.
